
CREATE TABLE LST_DISTRICTS (
  id int NOT NULL,
  p_code varchar(3) DEFAULT NULL,
  code varchar(3) DEFAULT NULL,
  name_value varchar(70) DEFAULT NULL,
  PRIMARY KEY (id)
)

INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('1',  '01', '01', 'CARMEN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('2',  '01', '02', 'MERCED');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('3',  '01', '03', 'HOSPITAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('4',  '01', '04', 'CATEDRAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('5',  '01', '05', 'ZAPOTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('6',  '01', '06', 'SAN FRANCISCO DE DOS RÍOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('7',  '01', '07', 'URUCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('8',  '01', '08', 'MATA REDONDA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('9',  '01', '09', 'PAVAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('10',  '01', '10', 'HATILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('11',  '01', '11', 'SAN SEBASTIÁN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('12',  '02', '01', 'ESCAZÚ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('13',  '02', '02', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('14',  '02', '03', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('15',  '03', '01', 'DESAMPARADOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('16',  '03', '02', 'SAN MIGUEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('17',  '03', '03', 'SAN JUAN DE DIOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('18',  '03', '04', 'SAN RAFAEL ARRIBA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('19',  '03', '05', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('20',  '03', '06', 'FRAILES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('21',  '03', '07', 'PATARRÁ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('22',  '03', '08', 'SAN CRISTÓBAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('23',  '03', '09', 'ROSARIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('24',  '03', '10', 'DAMAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('25',  '03', '11', 'SAN RAFAEL ABAJO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('26',  '03', '12', 'GRAVILIAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('27',  '03', '13', 'LOS GUIDO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('28',  '04', '01', 'SANTIAGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('29',  '04', '02', 'MERCEDES SUR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('30',  '04', '03', 'BARBACOAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('31',  '04', '04', 'GRIFO ALTO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('32',  '04', '05', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('33',  '04', '06', 'CANDELARITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('34',  '04', '07', 'DESAMPARADITOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('35',  '04', '08', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('36',  '04', '09', 'CHIRES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('37',  '05', '01', 'SAN MARCOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('38',  '05', '02', 'SAN LORENZO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('39',  '05', '03', 'SAN CARLOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('40',  '06', '01', 'ASERRI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('41',  '06', '02', 'TARBACA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('42',  '06', '03', 'VUELTA DE JORCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('43',  '06', '04', 'SAN GABRIEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('44',  '06', '05', 'LEGUA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('45',  '06', '06', 'MONTERREY');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('46',  '06', '07', 'SALITRILLOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('47',  '07', '01', 'COLÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('48',  '07', '02', 'GUAYABO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('49',  '07', '03', 'TABARCIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('50',  '07', '04', 'PIEDRAS NEGRAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('51',  '07', '05', 'PICAGRES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('52',  '07', '06', 'JARIS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('53',  '07', '07', 'QUITIRRISI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('54',  '08', '01', 'GUADALUPE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('55',  '08', '02', 'SAN FRANCISCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('56',  '08', '03', 'CALLE BLANCOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('57',  '08', '04', 'MATA DE PLÁTANO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('58',  '08', '05', 'IPÍS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('59',  '08', '06', 'RANCHO REDONDO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('60',  '08', '07', 'PURRAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('61',  '09', '01', 'SANTA ANA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('62',  '09', '02', 'SALITRAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('63',  '09', '03', 'POZOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('64',  '09', '04', 'URUCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('65',  '09', '05', 'PIEDADES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('66',  '09', '06', 'BRASIL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('67',  '10', '01', 'ALAJUELITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('68',  '10', '02', 'SAN JOSECITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('69',  '10', '03', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('70',  '10', '04', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('71',  '10', '05', 'SAN FELIPE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('72',  '11', '01', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('73',  '11', '02', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('74',  '11', '03', 'DULCE NOMBRE DE JESÚS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('75',  '11', '04', 'PATALILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('76',  '11', '05', 'CASCAJAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('77',  '12', '01', 'SAN IGNACIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('78',  '12', '02', 'GUAITIL Villa');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('79',  '12', '03', 'PALMICHAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('80',  '12', '04', 'CANGREJAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('81',  '12', '05', 'SABANILLAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('82',  '13', '01', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('83',  '13', '02', 'CINCO ESQUINAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('84',  '13', '03', 'ANSELMO LLORENTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('85',  '13', '04', 'LEON XIII');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('86',  '13', '05', 'COLIMA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('87',  '14', '01', 'SAN VICENTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('88',  '14', '02', 'SAN JERÓNIMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('89',  '14', '03', 'LA TRINIDAD');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('90',  '15', '01', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('91',  '15', '02', 'SABANILLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('92',  '15', '03', 'MERCEDES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('93',  '15', '04', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('94',  '16', '01', 'SAN PABLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('95',  '16', '02', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('96',  '16', '03', 'SAN JUAN DE MATA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('97',  '16', '04', 'SAN LUIS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('98',  '16', '05', 'CARARA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('99',  '17', '01', 'SANTA MARÍA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('100',  '17', '02', 'JARDÍN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('101',  '17', '03', 'COPEY');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('102',  '18', '01', 'CURRIDABAT');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('103',  '18', '02', 'GRANADILLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('104',  '18', '03', 'SÁNCHEZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('105',  '18', '04', 'TIRRASES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('106',  '19', '01', 'SAN ISIDRO DE EL GENERAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('107',  '19', '02', 'EL GENERAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('108',  '19', '03', 'DANIEL FLORES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('109',  '19', '04', 'RIVAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('110',  '19', '05', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('111',  '19', '06', 'PLATANARES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('112',  '19', '07', 'PEJIBAYE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('113',  '19', '08', 'CAJÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('114',  '19', '09', 'BARÚ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('115',  '19', '10', 'RÍO NUEVO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('116',  '19', '11', 'PÁRAMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('117',  '20', '01', 'SAN PABLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('118',  '20', '02', 'SAN ANDRÉS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('119',  '20', '03', 'LLANO BONITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('120',  '20', '04', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('121',  '20', '05', 'SANTA CRUZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('122',  '20', '06', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('123',  '21', '01', 'ALAJUELA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('124',  '21', '02', 'SAN JOSÉ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('125',  '21', '03', 'CARRIZAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('126',  '21', '04', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('127',  '21', '05', 'GUÁCIMA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('128',  '21', '06', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('129',  '21', '07', 'SABANILLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('130',  '21', '08', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('131',  '21', '09', 'RÍO SEGUNDO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('132',  '21', '10', 'DESAMPARADOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('133',  '21', '11', 'TURRÚCARES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('134',  '21', '12', 'TAMBOR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('135',  '21', '13', 'GARITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('136',  '21', '14', 'SARAPIQUÍ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('137',  '22', '01', 'SAN RAMÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('138',  '22', '02', 'SANTIAGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('139',  '22', '03', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('140',  '22', '04', 'PIEDADES NORTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('141',  '22', '05', 'PIEDADES SUR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('142',  '22', '06', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('143',  '22', '07', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('144',  '22', '08', 'ÁNGELES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('145',  '22', '09', 'ALFARO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('146',  '22', '10', 'VOLIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('147',  '22', '11', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('148',  '22', '12', 'ZAPOTAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('149',  '22', '13', 'PEÑAS BLANCAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('150',  '23', '01', 'GRECIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('151',  '23', '02', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('152',  '23', '03', 'SAN JOSÉ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('153',  '23', '04', 'SAN ROQUE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('154',  '23', '05', 'TACARES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('155',  '23', '06', 'RÍO CUARTO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('156',  '23', '07', 'PUENTE DE PIEDRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('157',  '23', '08', 'BOLÍVAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('158',  '24', '01', 'SAN MATEO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('159',  '24', '02', 'DESMONTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('160',  '24', '03', 'JESÚS MARÍA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('161',  '24', '04', 'LABRADOR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('162',  '25', '01', 'ATENAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('163',  '25', '02', 'JESÚS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('164',  '25', '03', 'MERCEDES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('165',  '25', '04', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('166',  '25', '05', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('167',  '25', '06', 'SAN JOSE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('168',  '25', '07', 'SANTA EULALIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('169',  '25', '08', 'ESCOBAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('170',  '26', '01', 'NARANJO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('171',  '26', '02', 'SAN MIGUEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('172',  '26', '03', 'SAN JOSÉ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('173',  '26', '04', 'CIRRÍ SUR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('174',  '26', '05', 'SAN JERÓNIMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('175',  '26', '06', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('176',  '26', '07', 'EL ROSARIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('177',  '26', '08', 'PALMITOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('178',  '27', '01', 'PALMARES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('179',  '27', '02', 'ZARAGOZA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('180',  '27', '03', 'BUENOS AIRES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('181',  '27', '04', 'SANTIAGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('182',  '27', '05', 'CANDELARIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('183',  '27', '06', 'ESQUÍPULAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('184',  '27', '07', 'LA GRANJA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('185',  '28', '01', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('186',  '28', '02', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('187',  '28', '03', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('188',  '28', '04', 'CARRILLOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('189',  '28', '05', 'SABANA REDONDA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('190',  '29', '01', 'OROTINA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('191',  '29', '02', 'EL MASTATE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('192',  '29', '03', 'HACIENDA VIEJA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('193',  '29', '04', 'COYOLAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('194',  '29', '05', 'LA CEIBA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('195',  '30', '01', 'QUESADA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('196',  '30', '02', 'FLORENCIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('197',  '30', '03', 'BUENAVISTA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('198',  '30', '04', 'AGUAS ZARCAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('199',  '30', '05', 'VENECIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('200',  '30', '06', 'PITAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('201',  '30', '07', 'LA FORTUNA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('202',  '30', '08', 'LA TIGRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('203',  '30', '09', 'LA PALMERA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('204',  '30', '10', 'VENADO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('205',  '30', '11', 'CUTRIS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('206',  '30', '12', 'MONTERREY');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('207',  '30', '13', 'POCOSOL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('208',  '31', '01', 'ZARCERO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('209',  '31', '02', 'LAGUNA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('210',  '31', '04', 'GUADALUPE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('211',  '31', '05', 'PALMIRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('212',  '31', '06', 'ZAPOTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('213',  '31', '07', 'BRISAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('214',  '32', '01', 'SARCHÍ NORTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('215',  '32', '02', 'SARCHÍ SUR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('216',  '32', '03', 'TORO AMARILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('217',  '32', '04', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('218',  '32', '05', 'RODRÍGUEZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('219',  '33', '01', 'UPALA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('220',  '33', '02', 'AGUAS CLARAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('221',  '33', '03', 'SAN JOSÉ o PIZOTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('222',  '33', '04', 'BIJAGUA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('223',  '33', '05', 'DELICIAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('224',  '33', '06', 'DOS RÍOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('225',  '33', '07', 'YOLILLAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('226',  '33', '08', 'CANALETE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('227',  '34', '01', 'LOS CHILES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('228',  '34', '02', 'CAÑO NEGRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('229',  '34', '03', 'EL AMPARO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('230',  '34', '04', 'SAN JORGE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('231',  '35', '02', 'BUENAVISTA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('232',  '35', '03', 'COTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('233',  '35', '04', 'KATIRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('234',  '36', '01', 'ORIENTAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('235',  '36', '02', 'OCCIDENTAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('236',  '36', '03', 'CARMEN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('237',  '36', '04', 'SAN NICOLÁS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('238',  '36', '05', 'AGUACALIENTE o SAN FRANCISCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('239',  '36', '06', 'GUADALUPE o ARENILLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('240',  '36', '07', 'CORRALILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('241',  '36', '08', 'TIERRA BLANCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('242',  '36', '09', 'DULCE NOMBRE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('243',  '36', '10', 'LLANO GRANDE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('244',  '36', '11', 'QUEBRADILLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('245',  '37', '01', 'PARAÍSO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('246',  '37', '02', 'SANTIAGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('247',  '37', '03', 'OROSI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('248',  '37', '04', 'CACHÍ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('249',  '37', '05', 'LLANOS DE SANTA LUCÍA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('250',  '38', '01', 'TRES RÍOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('251',  '38', '02', 'SAN DIEGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('252',  '38', '03', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('253',  '38', '04', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('254',  '38', '05', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('255',  '38', '06', 'DULCE NOMBRE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('256',  '38', '07', 'SAN RAMÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('257',  '38', '08', 'RÍO AZUL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('258',  '39', '01', 'JUAN VIÑAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('259',  '39', '02', 'TUCURRIQUE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('260',  '39', '03', 'PEJIBAYE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('261',  '40', '01', 'TURRIALBA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('262',  '40', '02', 'LA SUIZA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('263',  '40', '03', 'PERALTA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('264',  '40', '04', 'SANTA CRUZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('265',  '40', '05', 'SANTA TERESITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('266',  '40', '06', 'PAVONES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('267',  '40', '07', 'TUIS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('268',  '40', '08', 'TAYUTIC');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('269',  '40', '09', 'SANTA ROSA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('270',  '40', '10', 'TRES EQUIS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('271',  '40', '11', 'LA ISABEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('272',  '40', '12', 'CHIRRIPÓ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('273',  '41', '01', 'PACAYAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('274',  '41', '02', 'CERVANTES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('275',  '41', '03', 'CAPELLADES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('276',  '42', '01', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('277',  '42', '02', 'COT');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('278',  '42', '03', 'POTRERO CERRADO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('279',  '42', '04', 'CIPRESES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('280',  '42', '05', 'SANTA ROSA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('281',  '43', '01', 'EL TEJAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('282',  '43', '02', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('283',  '43', '03', 'TOBOSI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('284',  '43', '04', 'PATIO DE AGUA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('285',  '44', '01', 'HEREDIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('286',  '44', '02', 'MERCEDES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('287',  '44', '03', 'SAN FRANCISCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('288',  '44', '04', 'ULLOA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('289',  '44', '05', 'VARABLANCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('290',  '45', '01', 'BARVA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('291',  '45', '02', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('292',  '45', '03', 'SAN PABLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('293',  '45', '04', 'SAN ROQUE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('294',  '45', '05', 'SANTA LUCÍA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('295',  '45', '06', 'SAN JOSÉ DE LA MONTAÑA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('296',  '46', '02', 'SAN VICENTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('297',  '46', '03', 'SAN MIGUEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('298',  '46', '04', 'PARACITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('299',  '46', '05', 'SANTO TOMÁS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('300',  '46', '06', 'SANTA ROSA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('301',  '46', '07', 'TURES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('302',  '46', '08', 'PARÁ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('303',  '47', '01', 'SANTA BÁRBARA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('304',  '47', '02', 'SAN PEDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('305',  '47', '03', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('306',  '47', '04', 'JESÚS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('307',  '47', '05', 'SANTO DOMINGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('308',  '47', '06', 'PURABÁ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('309',  '48', '01', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('310',  '48', '02', 'SAN JOSECITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('311',  '48', '03', 'SANTIAGO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('312',  '48', '04', 'ÁNGELES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('313',  '48', '05', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('314',  '49', '01', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('315',  '49', '02', 'SAN JOSÉ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('316',  '49', '03', 'CONCEPCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('317',  '49', '04', 'SAN FRANCISCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('318',  '50', '01', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('319',  '50', '02', 'LA RIBERA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('320',  '50', '03', 'LA ASUNCIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('321',  '51', '01', 'SAN JOAQUÍN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('322',  '51', '02', 'BARRANTES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('323',  '51', '03', 'LLORENTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('324',  '52', '01', 'SAN PABLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('325',  '53', '01', 'PUERTO VIEJO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('326',  '53', '02', 'LA VIRGEN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('327',  '53', '03', 'LAS HORQUETAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('328',  '53', '04', 'LLANURAS DEL GASPAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('329',  '53', '05', 'CUREÑA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('330',  '54', '01', 'LIBERIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('331',  '54', '02', 'CAÑAS DULCES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('332',  '54', '03', 'MAYORGA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('333',  '54', '04', 'NACASCOLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('334',  '54', '05', 'CURUBANDÉ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('335',  '55', '01', 'NICOYA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('336',  '55', '02', 'MANSIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('337',  '55', '03', 'SAN ANTONIO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('338',  '55', '04', 'QUEBRADA HONDA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('339',  '55', '05', 'SÁMARA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('340',  '55', '06', 'NOSARA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('341',  '55', '07', 'BELÉN DE NOSARITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('342',  '56', '01', 'SANTA CRUZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('343',  '56', '02', 'BOLSÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('344',  '56', '03', 'VEINTISIETE DE ABRIL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('345',  '56', '04', 'TEMPATE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('346',  '56', '05', 'CARTAGENA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('347',  '56', '06', 'CUAJINIQUIL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('348',  '56', '07', 'DIRIÁ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('349',  '56', '08', 'CABO VELAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('350',  '56', '09', 'TAMARINDO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('351',  '57', '01', 'BAGACES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('352',  '57', '02', 'LA FORTUNA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('353',  '57', '03', 'MOGOTE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('354',  '57', '04', 'RÍO NARANJO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('355',  '58', '01', 'FILADELFIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('356',  '58', '02', 'PALMIRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('357',  '58', '03', 'SARDINAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('358',  '58', '04', 'BELÉN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('359',  '59', '01', 'CAÑAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('360',  '59', '02', 'PALMIRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('361',  '59', '03', 'SAN MIGUEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('362',  '59', '04', 'BEBEDERO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('363',  '59', '05', 'POROZAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('364',  '60', '01', 'LAS JUNTAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('365',  '60', '02', 'SIERRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('366',  '60', '03', 'SAN JUAN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('367',  '60', '04', 'COLORADO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('368',  '61', '01', 'TILARÁN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('369',  '61', '02', 'QUEBRADA GRANDE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('370',  '61', '03', 'TRONADORA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('371',  '61', '04', 'SANTA ROSA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('372',  '61', '05', 'LÍBANO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('373',  '61', '06', 'TIERRAS MORENAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('374',  '61', '07', 'ARENAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('375',  '62', '01', 'CARMONA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('376',  '62', '02', 'SANTA RITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('377',  '62', '03', 'ZAPOTAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('378',  '62', '04', 'SAN PABLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('379',  '62', '05', 'PORVENIR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('380',  '62', '06', 'BEJUCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('381',  '63', '01', 'LA CRUZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('382',  '63', '02', 'SANTA CECILIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('383',  '63', '03', 'LA GARITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('384',  '63', '04', 'SANTA ELENA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('385',  '64', '01', 'HOJANCHA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('386',  '64', '02', 'MONTE ROMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('387',  '64', '03', 'PUERTO CARRILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('388',  '64', '04', 'HUACAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('389',  '65', '01', 'PUNTARENAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('390',  '65', '02', 'PITAHAYA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('391',  '65', '03', 'CHOMES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('392',  '65', '04', 'LEPANTO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('393',  '65', '05', 'PAQUERA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('394',  '65', '06', 'MANZANILLO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('395',  '65', '07', 'GUACIMAL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('396',  '65', '08', 'BARRANCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('397',  '65', '09', 'MONTE VERDE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('398',  '65', '11', 'CÓBANO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('399',  '65', '12', 'CHACARITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('400',  '65', '13', 'CHIRA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('401',  '65', '14', 'ACAPULCO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('402',  '65', '15', 'EL ROBLE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('403',  '65', '16', 'ARANCIBIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('404',  '66', '01', 'ESPÍRITU SANTO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('405',  '66', '02', 'SAN JUAN GRANDE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('406',  '66', '03', 'MACACONA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('407',  '66', '04', 'SAN RAFAEL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('408',  '66', '05', 'SAN JERÓNIMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('409',  '66', '06', 'CALDERA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('410',  '67', '01', 'BUENOS AIRES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('411',  '67', '02', 'VOLCÁN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('412',  '67', '03', 'POTRERO GRANDE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('413',  '67', '04', 'BORUCA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('414',  '67', '05', 'PILAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('415',  '67', '06', 'COLINAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('416',  '67', '07', 'CHÁNGUENA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('417',  '67', '08', 'BIOLLEY');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('418',  '67', '09', 'BRUNKA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('419',  '68', '01', 'MIRAMAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('420',  '68', '02', 'LA UNIÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('421',  '68', '03', 'SAN ISIDRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('422',  '69', '01', 'PUERTO CORTÉS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('423',  '69', '02', 'PALMAR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('424',  '69', '03', 'SIERPE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('425',  '69', '04', 'BAHÍA BALLENA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('426',  '69', '05', 'PIEDRAS BLANCAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('427',  '69', '06', 'BAHÍA DRAKE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('428',  '70', '01', 'QUEPOS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('429',  '70', '02', 'SAVEGRE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('430',  '70', '03', 'NARANJITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('431',  '71', '01', 'GOLFITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('432',  '71', '02', 'PUERTO JIMÉNEZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('433',  '71', '03', 'GUAYCARÁ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('434',  '71', '04', 'PAVÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('435',  '72', '01', 'SAN VITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('436',  '72', '02', 'SABALITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('437',  '72', '03', 'AGUABUENA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('438',  '72', '04', 'LIMONCITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('439',  '72', '05', 'PITTIER');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('440',  '72', '06', 'GUTIERREZ BRAUN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('441',  '73', '01', 'PARRITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('442',  '74', '01', 'CORREDOR');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('443',  '74', '02', 'LA CUESTA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('444',  '74', '03', 'CANOAS');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('445',  '74', '04', 'LAUREL');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('446',  '75', '01', 'JACÓ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('447',  '75', '02', 'TÁRCOLES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('448',  '76', '01', 'LIMÓN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('449',  '76', '02', 'VALLE LA ESTRELLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('450',  '76', '04', 'MATAMA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('451',  '77', '01', 'GUÁPILES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('452',  '77', '02', 'JIMÉNEZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('453',  '77', '03', 'RITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('454',  '77', '04', 'ROXANA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('455',  '77', '05', 'CARIARI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('456',  '77', '06', 'COLORADO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('457',  '77', '07', 'LA COLONIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('458',  '78', '01', 'SIQUIRRES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('459',  '78', '02', 'PACUARITO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('460',  '78', '03', 'FLORIDA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('461',  '78', '04', 'GERMANIA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('462',  '78', '05', 'EL CAIRO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('463',  '78', '06', 'ALEGRÍA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('464',  '79', '01', 'BRATSI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('465',  '79', '02', 'SIXAOLA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('466',  '79', '03', 'CAHUITA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('467',  '79', '04', 'TELIRE');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('468',  '80', '01', 'MATINA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('469',  '80', '02', 'BATÁN');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('470',  '80', '03', 'CARRANDI');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('471',  '81', '01', 'GUÁCIMO');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('472',  '81', '02', 'MERCEDES');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('473',  '81', '03', 'POCORA');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('474',  '81', '04', 'RÍO JIMÉNEZ');
INSERT INTO LST_DISTRICTS (id, p_code,  code, name_value) VALUES ('475',  '81', '05', 'DUACARÍ');


